name: Shopify Lighthouse CI
on:
  pull_request:
    branches: [ main ]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
        store: ${{ secrets.SHOP_STORE }}
        password: ${{ secrets.SHOP_PASSWORD }}
